language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project= test/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      name: "HTML"
      after_success: skip

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
